// Barrel export for section components
export { default as SectionHeader } from './SectionHeader'
export { default as FeatureSection } from './FeatureSection'
export { default as GridContainer } from './GridContainer'
export { default as HeroSlider } from './HeroSlider'
export { default as PartnershipsSection } from './PartnershipsSection'
export { default as AwardsSection } from './AwardsSection'
export { default as PillarsSection } from './PillarsSection'
export { default as CurriculumSection } from './CurriculumSection'
export { default as GallerySection } from './GallerySection'
export { default as AlumniCarousel } from './AlumniCarousel'
export { default as ActivitiesSection } from './ActivitiesSection'
export { default as NewsletterSection } from './NewsletterSection'
export { default as AdmissionsCtaSection } from './AdmissionsCtaSection'
